### ISSUE TITLE
Stop extra js/css loading (from the xhr request)

### ISSUE THREAD

**Issue by Aunuxx** [CloudStrifera/MaCalc#10]
Split from v0.6.2 since it doesn't directly effect clients

The current way of collecting score data from classes page uses a XMLHttpRequest (xhr)
It appears the xhr loads js/css/img witch show up in console
The js/css errors are due to not being used and the img is due to cross site protection

I don't think it affects out 3rd party script use (for chrome web extensions)

TLDR;
Do the log messages matter?
Is there a fix?

**Comment by HyperOG** [comment]
What do you mean log messages?

**Comment by Aunuxx** [comment]
> What do you mean log messages?

have a look at the inspect console on the classes page

**Comment by Aunuxx** [comment]
false err,
I saw the classes.js send an err, this was not macalc classes.js but the pages classes.js
macalc js files will be renamed to macalc_xxxx to reduce confusion
