### ISSUE TITLE
0.6.2 - Last update before release

### ISSUE THREAD

**Issue by HyperOG** [CloudStrifera/MaCalc#12]
Bug Report:

0.6.1 Additions Report #9 - Everything works Ok

External Bugs found - 1 
![image](https://github.com/CloudStrifera/MaCalc/assets/146312508/6e52a032-1fb3-43c6-85e0-050b4b27e650)

External Bugs Fixed - 1 (0.6.1 Additions Report #9) : 

Fixed bug where the menu would not keep the user selection on the extention outlay, however will remeber the user selection on the actual progress page

Changes/Additions:

Addition to the General Menu - Wheel Toggle, List Flip, Banded colors (White, Gray alternating for each subject respectivly)

**Comment by Aunuxx** [comment]
Should have fixed the issue
(using 180 instead of letter bc it was copy from list flip)
