### ISSUE TITLE
Additions/Fixes for Update 0.6.1

### ISSUE THREAD

**Issue by Aunuxx** [CloudStrifera/MaCalc#4]
Additions:
- [x] GPA section in Grade overview
- [x] Letter in Grade overview
- [x] Category score
- [x] icon

Fixes:
- [x] Fix Chrome err message for previously declared const (when switching between overview and a class progress)
- [x] Fix GPA load method for wheel #7

**Comment by HyperOG** [comment]
0.6.1 error:

No longer showes SBL grade or letter grade in mastry tracker
![image](https://github.com/CloudStrifera/MaCalc/assets/146312508/faabb7d1-759c-4be6-acc9-12fe861a14b4)

To replicate:
Go to any subject mastery tracker progress



ISSUE HAS BEEN RESOLVED

**Comment by HyperOG** [comment]
what was the err message for chrome?

**Comment by Aunuxx** [comment]
```Uncaught SyntaxError: Identifier 'cat_path' has already been declared``` 
you can recreate it by moving to classes then a progress

**Comment by HyperOG** [comment]
Chrome Err mesg:

![image](https://github.com/CloudStrifera/MaCalc/assets/146312508/45f21122-cd36-4545-a528-6433ebcaec7e)

that's for all classes or how many were opened

Potential Fix:
Since there are two cat paths, we can attempt to change one of their names to somthing diffrent

**Comment by Aunuxx** [comment]
have a redownload and see if that works for you (limited vars to local)

**Comment by HyperOG** [comment]
its still bugged 
![image](https://github.com/CloudStrifera/MaCalc/assets/146312508/9110da2e-dfe7-46f8-aeaa-a950c0cc3884)

**Comment by Aunuxx** [comment]
none of those are the extention, if you dont see anything in the extensions page then it should be resolved

**Comment by HyperOG** [comment]
Bug Fixed: Error message from chrome ```Uncaught SyntaxError: Identifier 'cat_path' has already been declared```
![image](https://github.com/CloudStrifera/MaCalc/assets/146312508/0aac6eab-8ef5-41cf-898b-eab45084783f)

**Comment by HyperOG** [comment]
what icon did you add?

**Comment by Aunuxx** [comment]
> what icon did you add?

Have a look at the icons folder
