### ISSUE TITLE
0.6.1 error:

### ISSUE THREAD

**Issue by Aunuxx** [CloudStrifera/MaCalc#6]
0.6.1 error:

No longer showes SBL grade or letter grade in mastry tracker
![image](https://github.com/CloudStrifera/MaCalc/assets/146312508/faabb7d1-759c-4be6-acc9-12fe861a14b4)

To replicate:
Go to any subject mastery tracker progress

_Originally posted by @HyperOG in https://github.com/CloudStrifera/MaCalc/issues/4#issuecomment-2065785042_

**Comment by Aunuxx** [comment]
what site are you using? (Canvas or MC)

**Comment by HyperOG** [comment]
Mastry tracker through canvas

<img width="668" alt="image" src="https://github.com/CloudStrifera/MaCalc/assets/146312508/480de219-5b47-4a25-a9f5-6c05fa7352ca">

![image](https://github.com/CloudStrifera/MaCalc/assets/146312508/066a5678-7303-403f-bd9c-3dee6a397bc6)

**Comment by Aunuxx** [comment]
can you inspect element > console > any logs with progress.js on the right
and inspect > elements > select anyware within the MT page and look for a tag called `#document` and send back the url associated

**Comment by HyperOG** [comment]
MT page? Mastry tracker?

**Comment by Aunuxx** [comment]
Yes

**Comment by HyperOG** [comment]
2 things:

![image](https://github.com/CloudStrifera/MaCalc/assets/146312508/7a71d7e8-1760-475a-9b9e-7b25c5bbcde9)

![image](https://github.com/CloudStrifera/MaCalc/assets/146312508/cbbf4075-4965-45db-ab1a-96768138f757)

**Comment by Aunuxx** [comment]
can you also send your manifest.json, in the archive you unzipped to load it (paste in and surround with triple back ticks on each end: \`\`\`json  manifest here \`\`\`)

**Comment by HyperOG** [comment]
```[manifest.json](https://github.com/CloudStrifera/MaCalc/files/15033553/manifest.json)```

fuck or is that correct?

**Comment by HyperOG** [comment]
[manifest.json](https://github.com/CloudStrifera/MaCalc/files/15033556/manifest.json)

**Comment by Aunuxx** [comment]
the manifest was updated to fix the issue just after i had you download it, redownload from the master or the v0.6.0 release and it should fix the issue

**Comment by HyperOG** [comment]
Still bugged

![image](https://github.com/CloudStrifera/MaCalc/assets/146312508/c032fc9e-d88b-483b-b49e-dca1f6e1004f)

**Comment by HyperOG** [comment]
Errors given:

![image](https://github.com/CloudStrifera/MaCalc/assets/146312508/36ca22df-db05-4982-9834-8d6c00c1161e)

also how the hell do i change inspect font it looks really stupid and is hard to read

**Comment by Aunuxx** [comment]
sorry, i had fixed on my local machine and forgotten to push to the master, have another go redownloading and see what happens

**Comment by HyperOG** [comment]
Issue resovled:

Bug fixed with Mastry Wheel not showing SBL grading  and Letter grade
![image](https://github.com/CloudStrifera/MaCalc/assets/146312508/11f44a20-4996-43d6-a801-65270e06d770)
